### ISSUE TITLE
Export only symbols that are needed

### ISSUE THREAD

**Issue by kmilos** [google/libultrahdr#103]
Compared to `ultrahdr_api.h`, the shared object, e.g. `libuhdr.dll`, exposes everything in the library.

Cf. https://gcc.gnu.org/wiki/Visibility

**Comment by ram-mohan** [comment]
This is a known issue. ultrahdr_api.h is a recently introduced interface. Before that, there were applications which are including the header files in include folder directly. 

For instance, https://cs.android.com/android/platform/superproject/main/+/main:frameworks/av/services/camera/libcameraservice/api2/JpegRCompositeStream.cpp?q=%23include%20%22ultrahdr%2Fjpegr.h%22&start=11

Once all the applications are ported to use ultrahdr_api.h, we will address this.
