### ISSUE TITLE
Request: Support for 1:1 (and 1:2) resolution gain maps

### ISSUE THREAD

**Issue by gregbenz** [google/libultrahdr#121]
When encoding, the output always seems to be a gain map with 1:4 resolution. This can cause unwanted artifacts in high frequency detail. It would be ideal to have options for 1:1 and 1:2 resolution.

**Comment by DichenZhang1** [comment]
Hi Greg. Currently it is fixed to 4, to change it you'll need to change it in the code and build the library. We are now developing the version 2 version of the library and reading this parameter from user input will be available in v2.

**Comment by gregbenz** [comment]
@DichenZhang1 Thank you for pointing out that place in the code. Looking forward to v2, sounds like the team has lots of great updates planned. Truly appreciate all you're doing!
