### ISSUE TITLE
The srgbRgbToYuv conversion issue in JpegR::toneMap

### ISSUE THREAD

**Issue by jeyden** [google/libultrahdr#149]
When the color gamut of source image is BT.2100, hdrGamutConversionFn is bt2100ToP3. However, in the final step of converting from RGB to YUV format, it uses the function srgbRgbToYuv. I think function p3RgbToYuv should be used for the yuv conversion to match the previously transformed color gamut. Here is my reasoning:

srgbRgbToYuv uses the transformation coefficients in ITU-R BT.709-6, so the input of the function should comply with BT.709. I know that there are some cases where P3 and BT.601 are interpreted similarly in this library, and BT601_625 has the same color primaries with BT.709. In this case, if bt2100ToP3 is same with to BT.601 and BT.709, srgbRgbToYuv is right. I want to confirm if P3 is BT.601_625 in this case by reviewing the ITU-R BT.2407 and EG 432-1 documents, but can not find the P3 related coefficients. However,  I found bt2100ToBt709 coefficients in ITU-R BT.2407, they match perfectly and are diffenent from bt2100ToP3`s coefficients.Therefore, in conclusion, I believe the output of the function bt2100ToP3 is truely P3 gamut, srgbRgbToYuv  is incorrect in this context.

Looking forward to your reply. Thx.

**Comment by DichenZhang1** [comment]
Hi @jeyden ,

Yes this is an error in the tone mapping method. Thank you for this good catch. I've fixed in [this PR](https://github.com/google/libultrahdr/pull/155).

Thank you!
Dichen
