### ISSUE TITLE
Google Pixel8 images fail to open

### ISSUE THREAD

**Issue by MajorMurphy** [google/libultrahdr#152]
Images generated with the Pixel8 Pro camera fail to open here:  
https://github.com/google/libultrahdr/blob/94fbd77105cf5dc0e73b85060b2a065576bbf7a6/lib/src/jpegr.cpp#L1143
Image: 4080x3072 (ratio 1.318125)
Gain Map: 540x406 (ratio 1.33004...)

![PXL_20240318_183908407](https://github.com/google/libultrahdr/assets/1276140/dcf293c0-2105-4511-a8c8-aa7491fad242)

I'll to share my solution as a pull request.

**Comment by DichenZhang1** [comment]
Hi @MajorMurphy , thank you for raising this issue and providing the fix. Could you send me the image attached? (cannot be opened or downloaded on my side). Thank you!

**Comment by DichenZhang1** [comment]
The issue should be fixed by https://github.com/google/libultrahdr/pull/154, could you give it a try and let me know the result? Thank you!

**Comment by DichenZhang1** [comment]
@MajorMurphy thanks for the reply. Never mind I know this issue and it should already been fixed by my recent PRs.
