### ISSUE TITLE
Encode Scenario 4 : Missing Parameters

### ISSUE THREAD

**Issue by pmonck** [google/libultrahdr#157]
Using the example command:
ultrahdr_app -m 0 -i cosmat_1920x1080_420_8bit.jpg -g cosmat_1920x1080_420_8bit.jpg -f metadata.cfg

results in:
did not receive valid image width for encoding. width :  0

It looks like the example should be modified to include width (-w) and height (-h) parameters as in the other encode scenarios.

**Comment by DichenZhang1** [comment]
Hi @pmonck,

Thank you for raising this issue! The width/height should be read from in input JPEG images instead of reading from the configuration. However, this indeed a bug in the app, and it should be fixed by https://github.com/google/libultrahdr/pull/159

Thank you!

**Comment by DichenZhang1** [comment]
Close for now. Please re-open if there is further issue. Thank you!

**Comment by pmonck** [comment]
This issue seems to have reverted in the latest commit.

**Comment by ram-mohan** [comment]
looks like these changes were never merged in main. They were accidentally merged to a dev branch and the issue got closed.

**Comment by pmonck** [comment]
Thanks for looking into this. How should the issue be resolved?
