### ISSUE TITLE
Support Crop usecases

### ISSUE THREAD

**Issue by kkumar1994** [google/libultrahdr#167]
Support crop functionality inside the UHDR library. If the user were to feed in crop regions along with the input P010 and/or YUV420, JPEG the library should perform the crop operation based on the crop values provided.

**Comment by DichenZhang1** [comment]
Hi @kkumar1994, I believe the cropping method is already [here](https://github.com/google/libultrahdr/blob/main/lib/include/ultrahdr/editorhelper.h), could you let me know if there is any additional requests. Thank you!

**Comment by kkumar1994** [comment]
Hi, yes that's exactly what I was thinking about. I hoped to contribute to
the project by implementing this feature but it looks like you guys beat me
to it :)

**Comment by DichenZhang1** [comment]
Thank you for confirming. I'll close this thread now. If there is other requests, please feel free to reopen or file a new one. Thank you!
