### ISSUE TITLE
Issue while runing ultrahdr_app demo

### ISSUE THREAD

**Issue by jeremysong1106** [google/libultrahdr#21]
Hi,

I build the library successfully and try to run some hdr image with the ultrahdr_app demo, 

when I gave the command :
./ultrahdr_app -p ./data/Gain_Map_Sample_Photos/samples_avif/01.avif -w 2400 -h 3000 -o 0

and it showed the error message here when I run the avif file:
 requested to read 29752320 bytes from file : ./data/Gain_Map_Sample_Photossamples_avif/01.avif, file contains only 29752320 bytes

Can you help me to check why the issue comes? It would be great if you can provide an example how to use the demo.

Bests

**Comment by ram-mohan** [comment]
The sample application takes uncompressed yuv in p010 format as input.

./ultrahdr_app -p <uncompressed yuv in p010 format> -w <width> -h <height> -m 0

In data folder, there is a sample p010 input which can be used for testing purpose.

The application does not take compressed files (avif, heif, ...)

**Comment by jeremysong1106** [comment]
> The sample application takes uncompressed yuv in p010 format as input.
> 
> ./ultrahdr_app -p -w -h -m 0
> 
> In data folder, there is a sample p010 input which can be used for testing purpose.
> 
> The application does not take compressed files (avif, heif, ...)

could you tell you how can i check the width and height of the sample p010 image? thanks in advance :)

**Comment by ram-mohan** [comment]
Added a change that improves app usage
