### ISSUE TITLE
Ambiguous wording in ultrahdr_app help

### ISSUE THREAD

**Issue by pmonck** [google/libultrahdr#213]
I feel the description of ultrahdr_app's -M option is unclear.

I propose that

 "-M    enable / disable multi channel gain map, optional. [0:no (default), 1:yes]."

 be replaced with

 "-M    enable multi channel gain map, optional. [0:no (default), 1:yes]."

or

"-M    enable / disable multi channel gain map, optional. [0:disable (default), 1:enable]."

**Comment by ram-mohan** [comment]
@pmonck @DichenZhang1 the sample app is updated accordingly. This bug can be marked for closure.
