### ISSUE TITLE
Multiple MinGW build warnings

### ISSUE THREAD

**Issue by kmilos** [google/libultrahdr#248]
See e.g. MSYS2 UCRT64 (GCC 14.2) package build log:

https://github.com/msys2/MINGW-packages/actions/runs/10597101135/job/29366506161?pr=21769#step:11:319

Clang 18.1 in the CLANG64 environments seems to be silent:

https://github.com/msys2/MINGW-packages/actions/runs/10597101135/job/29366506516?pr=21769#step:11:303

**Comment by ram-mohan** [comment]
The warnings reported are false positives.
