### ISSUE TITLE
Malformed .pc file

### ISSUE THREAD

**Issue by kmilos** [google/libultrahdr#249]
If no EGL, results in
```
Libs.private:  EGL_LIBRARIES-NOTFOUND 
```
instead of an empty field.

**Comment by ram-mohan** [comment]
Thank you for pointing this out. Have uploaded a change that addresses this.

**Comment by ram-mohan** [comment]
Sorry I am new to this. Will take assistance and get these things resolved.

**Comment by ram-mohan** [comment]
@kmilos Thank you very much for pointing these.
