### ISSUE TITLE
Way to visualize rgba1010102 color format data

### ISSUE THREAD

**Issue by jeremysong1106** [google/libultrahdr#258]
Hi,

I'd like to visualize the decoded image while the output color format is hlg or pq, are there any ways support to visualize that?

thanks in advance.

**Comment by ram-mohan** [comment]
You can try with ffplay.
ffplay -color_range <value> -colorspace <value> -color_primaries <value> -f rawvideo -video_size wxh -pixel_format x2bgr10le -i hdrDecoded_rgba1010102.raw
