### ISSUE TITLE
Add version information to C API

### ISSUE THREAD

**Issue by cgohlke** [google/libultrahdr#268]
Hello,

thank you for developing this library as open source. I am adding an Ultra HDR codec based on `libultrahdr` to the [imagecodecs](https://github.com/cgohlke/imagecodecs/) Python package.

Would it be possible to add a means to obtain the libultrahdr library version using the C API? For example, add macros like `UHDR_VERSION_MAJOR` and `UHDR_VERSION_MINOR` or a `uhdr_version` function  to `ultrahdr_api.h`.

I would also like to second the [feature request raised in the discussion](https://github.com/google/libultrahdr/discussions/143), adding `float16` support to the encoder. Currently, the `uhdr_enc_set_raw_image` function fails with `'unsupported input pixel format for hdr intent 4, expects one of {UHDR_IMG_FMT_24bppYCbCrP010, UHDR_IMG_FMT_32bppRGBA1010102}'`.

**Comment by ram-mohan** [comment]
@cgohlke I have moved uhdr lib version macro to ultrahdr_api.h. Also documented semantic versioning details. Can you mark this closed if nothing related to versioning is pending and open a fresh request for adding support for color format rgbf16 for hdr intent . It is difficult to track multiple items in one request.

**Comment by ram-mohan** [comment]
@kmilos update the change [link](https://github.com/google/libultrahdr/pull/280/commits/e76bd1ca1ccf1407d6c484b9449737705f46df7f) to handle this.
