### ISSUE TITLE
Support for uneven dimensions

### ISSUE THREAD

**Issue by cmahnke** [google/libultrahdr#270]
See [this discussion](https://github.com/google/libultrahdr/discussions/246#discussioncomment-10602636) for the background:
Currently the dimensions of an image processed by `ultrahdr_app` (ant thus certainly the library itself) needs ho have even dimensions, otherwise an error like this is thrown:
```
image dimensions cannot be odd, received image dimensions
```

Support for uneven dimensions is needed

CC @ram-mohan

**Comment by ram-mohan** [comment]
Adding support for odd dimensions for color formats  UHDR_IMG_FMT_24bppYCbCrP010, UHDR_IMG_FMT_12bppYCbCr420 is an elaborate change. I have enabled odd dimension support for rgb inputs via this pull request #277

**Comment by ram-mohan** [comment]
If there is requirement/demand for adding even dimension support for yuv420 inputs as well then we can open a fresh request. For now, no changes are pending for this. The desired change is merged
