### ISSUE TITLE
Add support for encoding JPG as ISO 21496-1

### ISSUE THREAD

**Issue by gregbenz** [google/libultrahdr#271]
It appears the ISO gain map spec has progressed to draft international standard (https://www.iso.org/standard/86775.html), so I wanted to create a thread to facilitate discussion.

I believe the following will all be high value for libultra to support (ordered with most important first):
1. **encode** to ISO JPG. This is most important for content creation and is of course a prerequisite for the next item (transcoding).
2. **transcode** from supported gain map formats (Ultra HDR now, but ideally Apple too to support existing content from phone captures) to ISO JPG. For transcoding, as long as the image is not being mutated (cropping, etc), the output should be lossless (relative to the existing gain map). I presume all the metadata should map cleanly, and not recalculating the images is ideal for speed as well as quality.
3. **decode** ISO JPG.

**Comment by gregbenz** [comment]
Adobe's gain map page now refers to the ISO spec and contains sample JPG images which appear to use it (per the optional info overlay in the updated demo app on that page).
https://helpx.adobe.com/camera-raw/using/gain-map.html

**Comment by gregbenz** [comment]
I've added a sample ISO JPG here (currently listed as test 8a): https://gregbenzphotography.com/hdr/#tests

The latest ACR / LR updates from Adobe are able to export ISO gain maps for JPG, AVIF, and JXL.

**Comment by ram-mohan** [comment]
@gregbenz setting [this](https://github.com/google/libultrahdr/blob/cb0b016db8570d9b23aa7262042687bac47f9393/lib/src/jpegr.cpp#L56) to true should resolve this request.

**Comment by gregbenz** [comment]
@ram-mohan Thanks!!

**Comment by koto** [comment]
Are there plans to switch the flag on? Is this blocked on finalization of ISO 21496-1?

**Comment by ram-mohan** [comment]
@koto android recommends writing both xmp and iso metadata. details [here](https://developer.android.com/media/platform/hdr-image-format#iso_21496_1_compatibility). We have added a pr #329 to take care of this. thank you.

**Comment by mgenware** [comment]
Does Android use libultrahdr in camera app? Wondering why a [photo](https://www.gsmarena.com/realme_gt_7_pro-review-2763p5.php) taken from Android 15 has XMP but no ISO metadata.

![Image](https://github.com/user-attachments/assets/68c0e987-802c-4803-ad59-11fc24d86189)

While the adobe gain map [sample](https://helpx.adobe.com/camera-raw/using/gain-map.html) JPEG is opposite, has ISO but no XMP.

![Image](https://github.com/user-attachments/assets/8ec64e5d-569d-4149-bedf-730444f7b7cf)

Haven't found one JPEG with both XMP and ISO on internet 🤣

**Comment by mgenware** [comment]
@gregbenz thanks for the info! I can confirm iOS 18 JPEG and HEIC are both dual encoded.

HEIC:
![Image](https://github.com/user-attachments/assets/43f618ee-6326-4baa-8776-013015e15329)

JPEG:
![Image](https://github.com/user-attachments/assets/ade82b77-acdb-495e-a1eb-0c4de3049cea)
