### ISSUE TITLE
Parsing error when converting Lightroom exported ultrahdr

### ISSUE THREAD

**Issue by AdamMhm** [google/libultrahdr#284]
ultrahdr_app -m 1 -j testp3.jpg -f metadata.cfg
xml parse error, could not find attribute hdrgm:Version

When trying to convert a lightroom exported ultrahdr jpg to get a google ultrahdr metadata compliant version there is a parsing error. Source photo included.

[test p3_.zip](https://github.com/user-attachments/files/17080893/test.p3_.zip)

**Comment by koto** [comment]
This might be the same issue as #116. @AdamMhm, is there a way in Lightroom to export an UltraHDR with a 1-channel gainmap?

**Comment by ram-mohan** [comment]
Basing on the notes in, https://github.com/google/libultrahdr/issues/116#issuecomment-2287995683, this can be marked for closure.
