### ISSUE TITLE
Decode function does not work for Ultra hdr images created on pixel 6 pro

### ISSUE THREAD

**Issue by mcDandy** [google/libultrahdr#54]
I wanted to decompress image I took using my pixel 6 pro (UltraHDR option enabled, together with P2 colorspace, does not contain mjpeg stream with video). It gives me error hinting at added text encoding information of XMP information in the file.
```
$ ./ultrahdr_app -m 1 -j '/home/daniel/Desktop/PXL_20231230_110024323.jpg'
ERROR:Expected first character of a name
- line:1:<?xpacket begin="\xEF\xBB\xBF" id="W5M0MpCehiHzreSzNTczkc9d...
-         ^expected:Name
Encountered error during decodeJPEGR call, error code -20005
```

[PXL_20231230_110024323.jpg.tar.gz](https://github.com/google/libultrahdr/files/13798202/PXL_20231230_110024323.jpg.tar.gz)

**Comment by ram-mohan** [comment]
thank you for raising this issue. can you please try if the above patch set works.

**Comment by mcDandy** [comment]
It works, thank you.
I am however unable to open result raw (which has expacted size) and when converting back to jpeg, it looks wierd (red and blue stripes altering every pixel on top of what appears to be a luminance map)
![out](https://github.com/google/libultrahdr/assets/18588943/6d3720d7-0255-45f1-b656-ce45e7b56504)

**Comment by mcDandy** [comment]
I probably have wierd version of ffmpeg... (4.4.2-0ubuntu0.22.04.1)

[rawvideo @ 0x7efbac000cc0] No such pixel format: x2bgr10le.

Also is there any way to encode the file back to jpeg after editing it? 
`ultrahdr_app -m 0 -p outrgb.raw -C 1` uses wrong pixel format (result in my last post).

**Comment by ram-mohan** [comment]
That is an older version of ffmpeg. You can get an updated one here, https://github.com/ffbinaries/ffbinaries-prebuilt/releases.

Also is there any way to encode the file back to jpeg after editing it?
>> currently the encoder library does not take in rgb input. So for now it is not possible.  Having said that, we are working on few changes that would resolve this. very soon
