### ISSUE TITLE
Encoding error

### ISSUE THREAD

**Issue by suhailphotos** [google/libultrahdr#69]
I encountered an issue when combining the SDR base image with the YUV image. The error I received was "Encountered error during encodeJPEGR call, error code -20002." Interestingly, when I re-exported from Photoshop at a lower quality, everything worked smoothly.

I'm unsure if the problem is related to file size or chroma sampling rates like 4:2:0, or if there's another factor I'm not aware of. I've attached all four images for your reference.

**File details:**
1. Source (quality set to maximum -12): *trin_rain_acr_3d_gainmap.jpg* (3D gain map from Adobe Camera RAW 16.2)
2. YUV Conversion using FFMpeg: *trin_rain_converted_using_ffmpeg.yuv*
3. High-Quality SDR base (output from FFmpeg): *trin_rain_base_sdr_high_quality.jpeg*
4. Low-Quality (set to 5) re-export from Ps: *trin_rain_base_sdr_low_quality.jpg*

Combining images 2 and 3 failed, but combining 2 and 4 was successful.

The command used to run libultrahdr was: `./ultrahdr_app -m 0 -p trin_rain_converted_using_ffmpeg.yuv -i trin_rain_base_sdr_high_quality.jpeg -w 1080 -h 1350`

**FFmpeg version used:** 6.1.1

*Here is the link to the images:* [images link](https://www.dropbox.com/s/9lflknzmuafqs1e/Suhail_images.zip?dl=0)

**Comment by DichenZhang1** [comment]
Hi @ram-mohan @suhailphotos,

I believe this issue was fixed by one of our recent update. Could you check if we can close this issue?

Thank you!

**Comment by ram-mohan** [comment]
@DichenZhang1 Some more changes are needed. We are decoding the file but the data is 444. GenerateGainMap has to make use of this correctly. Currently I am working on this.

**Comment by DichenZhang1** [comment]
@ram-mohan OK thanks for the update!
