### ISSUE TITLE
Error when building

### ISSUE THREAD

**Issue by jeremysong1106** [google/libultrahdr#7]
Hi, 
I tried to build the code on my Ubuntu vm, and it said that the third party library doesn't exist, and I checked the folder again, the googletest and libjpeg-turbo is not pull from git.
I tried to manually pull the third party library and build it , then the error shows up :

undefined reference to `pthread_setspecific'
collect2: error: ld returned 1 exit status

am I building the code correctly? I'm looking forward to you helps,

Bests

**Comment by ram-mohan** [comment]
target_link_libraries(ultrahdr_unit_test
    ${SRC_DIR}/third_party/build/googletest/src/googletest-build/lib/libgmock.a
    ${SRC_DIR}/third_party/build/googletest/src/googletest-build/lib/libgtest.a
    ${SRC_DIR}/third_party/build/googletest/src/googletest-build/lib/libgtest_main.a
    pthread
)

can you add pthread to the list of libraries and see if it resolves the issue

**Comment by harishdm** [comment]
Hi @jeremysong1106, 
Thank you for reporting this issue. 
pthread dependency has been added in the latest commit. Can you please try with the latest commit? 

Also, for the issue with googletest and libjpeg-turbo not getting cloned in your VM setup, can you please confirm if your VM has git (version 1.6.5 or later) installed on it?
