### ISSUE TITLE
I am getting error -20008 when trying to decode image from ultrahdr

### ISSUE THREAD

**Issue by mcDandy** [google/libultrahdr#91]
Image taken on telephoto or ultrawide lens of pixel 6 pro does give this error. normal lens works fine.

![PXL_20240401_173044293 RAW-01 COVER](https://github.com/google/libultrahdr/assets/18588943/f567d574-d50f-45c1-bd7f-946d4af1eb28)

I checked the image and everything appears to be correct. Image has 4:2:0 chroma, google photos tell that it is UltraHDR.

**Comment by ram-mohan** [comment]
Thank you for reporting this. We know why this is happening. Recently we have made few changes that is causing this problem. We are working on addressing the same. Can you please share a link to access this image

**Comment by mcDandy** [comment]
https://github.com/google/libultrahdr/assets/18588943/f567d574-d50f-45c1-bd7f-946d4af1eb28

Github does not change uploaded image in any way. Will this suffice?

**Comment by ram-mohan** [comment]
extremely sorry for this additional work, the earlier shared image was sufficient. sorry again. will publish changes that would resolve this problem soon. thank you.

**Comment by mcDandy** [comment]
Dw. I posted the bug report under thé haze of sleepiness with replay after
5,5 hours of sleep...

Dne út 2. 4. 2024 7:16 uživatel ram ***@***.***> napsal:

**Comment by MajorMurphy** [comment]
@mcDandy, my solution #153 also fixes compatibility with your sample image file
