### ISSUE TITLE
Bundled libjpeg-turbo linkage seems to be hard-coded

### ISSUE THREAD

**Issue by kmilos** [google/libultrahdr#98]
I get this failure when trying to build on MSYS2 UCRT64:
```
ninja: error: 'C:/msys64/home/kmilos/MINGW-packages/mingw-w64-libultrahdr/src/libultrahdr-1.0.0/third_party/build/libjpeg-turbo/src/libjpeg-turbo-build/libjpeg.a', needed by 'ultrahdr_app.exe', missing and no known rule to make it
```

**Comment by kmilos** [comment]
Sorry, I see now things might be improved on main, while I was trying to package the 1.0.0 release...

Please tag and release these improvements when ready.

**Comment by ram-mohan** [comment]
On latest main this issue should not be seen. we are working on few more changes that further improve build and install process on different platforms. We will publish them in the earliest. For now I am closing this bug.
